[features]
seeds = false
skip-lint = false

# TODO: update to v2 addresses
[programs.localnet]
message_transmitter = "CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd"
token_messenger_minter = "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3"

[programs.devnet]
message_transmitter = "92HGLTqVgsbFtymx9t2YFp4vB5JUkEF7pF5V7LLoCVpE"
token_messenger_minter = "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3"

[programs.mainnet]
message_transmitter = "CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd"
token_messenger_minter = "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/v2/**/*.ts"

[workspace]
members = [
    "message-transmitter-v2",
    "token-messenger-minter-v2",
]

[toolchain]
anchor_version = "0.31.0" # `anchor-cli` version to use
solana_version = "2.1.0" # `solana-cli` version to use
