name: Miri

on:
  push:
    branches: master
  pull_request:
    branches: "*"
    
jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run with Miri
        run: cargo miri run
